// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK05w5yYcx5wLJyC3xsG8Sgnxba6Aa5bo',
    appId: '1:419855581264:web:02b9fb81a7ebab4118d155',
    messagingSenderId: '419855581264',
    projectId: 'price-tracker-flutter',
    authDomain: 'price-tracker-flutter.firebaseapp.com',
    storageBucket: 'price-tracker-flutter.firebasestorage.app',
    measurementId: 'G-XGTVR7GCDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDInxWnREwo2c3FFCk6pp8hK1Lo9nIixrg',
    appId: '1:419855581264:android:f36b4d2993f0ee1f18d155',
    messagingSenderId: '419855581264',
    projectId: 'price-tracker-flutter',
    storageBucket: 'price-tracker-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWup3uOn_ktC7M_auZ-0v88yjf1FZZBs',
    appId: '1:419855581264:ios:514c8c2841163e9118d155',
    messagingSenderId: '419855581264',
    projectId: 'price-tracker-flutter',
    storageBucket: 'price-tracker-flutter.firebasestorage.app',
    iosBundleId: 'com.example.priceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFWup3uOn_ktC7M_auZ-0v88yjf1FZZBs',
    appId: '1:419855581264:ios:514c8c2841163e9118d155',
    messagingSenderId: '419855581264',
    projectId: 'price-tracker-flutter',
    storageBucket: 'price-tracker-flutter.firebasestorage.app',
    iosBundleId: 'com.example.priceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK05w5yYcx5wLJyC3xsG8Sgnxba6Aa5bo',
    appId: '1:419855581264:web:edcc0cd030479dca18d155',
    messagingSenderId: '419855581264',
    projectId: 'price-tracker-flutter',
    authDomain: 'price-tracker-flutter.firebaseapp.com',
    storageBucket: 'price-tracker-flutter.firebasestorage.app',
    measurementId: 'G-22YDSK6WRX',
  );
}
